module.exports = [
    {
        id: 0,
        item_name: "Income",
        amount: 2350,
        date: "2023-03-31",
        from: "Employer",
        category: "Income",
        deposit: true
    },
    {
        id: 1,
        item_name: "Energy Bill",
        amount: 75,
        date: "2023-04-23",
        from: "Power Company",
        category: "Utilities",
        deposit: false,
    },
    {
        id: 2,
        item_name: "Groceries",
        amount: 210,
        date: "2023-04-03",
        from: "Grocery Store",
        category: "Food",
        deposit: false,
    },
    {
        id: 3,
        item_name: "Phone Bill",
        amount: 75,
        date: "2023-04-11",
        from: "T-Mobile",
        category: "Utilities",
        deposit: false,
    },
    {
        id: 4,
        item_name: "Playstation Online Membership",
        amount: 58,
        date: "2023-04-11",
        from: "Playstation Store",
        category: "Entertainment",
        deposit: false,
    },
    {
        id: 5,
        item_name: "Switch Online Membership",
        amount: 45,
        date: "2023-04-11",
        from: "Nintendo Store",
        category: "Entertainment",
        deposit: false,
    },
    {
        id: 6,
        item_name: "Movie Ticket",
        amount: 49,
        date: "2023-04-19",
        from: "Regal Theater",
        category: "Entertainment",
        deposit: false,
    },
    {
        id: 7,
        item_name: "Taxi",
        amount: 29,
        date: "2023-04-11",
        from: "Lyft",
        category: "Transportation",
        deposit: false,
    },
    {
        id: 8,
        item_name: "Laundry",
        amount: 15,
        date: "2023-04-16",
        from: "Wet & Dry Laundromat",
        category: "Miscellaneous",
        deposit: false,
    },
    {
        id: 9,
        item_name: "Food Tournament",
        amount: 40,
        date: "2023-04-04",
        from: "Date Weekend",
        category: "Miscellaneous",
        deposit: false,
    },
    {
        id: 10,
        item_name: "MetroCard",
        amount: 112,
        date: "2023-04-27",
        from: "MTA",
        category: "Transportation",
        deposit: false,
    },
];
